### ISSUE TITLE
Integrate and Report Content Validation

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/book-package-app#28]
Of interest to:
@BincyJ 
@birchamp 
@PhotoNomad0 
@RobH123 

Per brief discussion, the current thinking is to include a new table of results after/before the work count frequency table that shows results of the Content Validation RCL.

**Comment by RobH123** [comment]
@mandolyte Note that [content-validation](https://github.com/unfoldingWord/content-validation) is not an RCL, i.e., the core is pure JS functions and not designed as a component as such (because it was expected to be integrated into the tC Create workflow/UI at their discretion). Only the demo parts use React. The demos show three quite different ways that the results could possibly be displayed, but the check results are returned as an array of objects, intended to be manipulated further.
